### ISSUE TITLE
Crash if /usr/local/share/GeoIP/alias/ doesn't exist

### ISSUE THREAD

**Issue by hal3003** [cnbatch/GeoIP-Update-for-OPNsense#1]
Hi,

thank you very much for writing this tool. It's exactly what I was looking for since I don't want to accept the Maxmind Terms of Services.

I tried both compiling from source and downloading the binary, but either way it crashes with "Abort (core dumped)".

I then had a look at your code and found that the output gets copied to /usr/local/share/GeoIP/alias/ which didn't exist on my fresh installation of OPNsense.

So I created the folder and now it's working.

**Comment by cnbatch** [comment]
Thank you for feedback!
I've made a change to the code to fix this issue.
